### ISSUE TITLE
installation fails on Alpine Linux

### ISSUE THREAD

**Issue by bastistician** [mgondan/rswipl#2]
Compiling the libs succeeds, but then:
```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘rswipl’:
 .onLoad failed in loadNamespace() for 'rswipl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/mnt/QA/R-86380/lib/00LOCK-rswipl/00new/rswipl/libs/rswipl.so':
  Error loading shared library libswipl.so.9: No such file or directory (needed by /mnt/QA/R-86380/lib/00LOCK-rswipl/00new/rswipl/libs/rswipl.so)
Error: loading failed
Execution halted
```

This can be reproduced using, e.g., R-hub's [r-minimal](https://github.com/r-hub/r-minimal) Docker image:
```sh
docker run rhub/r-minimal  installr -c -a "cmake zlib-dev" rswipl
```

One problem seems to be in `.onLoad` here:

https://github.com/mgondan/rswipl/blob/a076daf22b63d0e0fc051dc2d48aa1c3c50a0e9f/R/rswipl.R#L38

which should also match "linux-musl" that is reported as `R.version$os` on Alpine Linux. I'd actually suggest to switch the if-else and detect the macOS case via `grepl("darwin", R.version$os)`.
(BTW, shouldn't `rswipl.ok <- TRUE` only be set if `libswipl` was found?)

Unfortunately, even after patching this such that `libswipl.so` is indeed in `getLoadedDLLs()`, loading still fails with the same error.

**Comment by mgondan** [comment]
Thank you, interesting. I reproduced your problem with `docker run rhub/r-minimal  installr -c -a "cmake zlib-dev" rswipl`. I guess it is easily fixed, but please help me with some docker basics: Suppose I have a local rswipl_9.3.3.2.tar.gz from R CMD build, how do I try it out in docker?

Sorry for bothering you with such a beginner question, but I think you have done the above anyway, so my question does not cause you meaningful extra work. 

For the record, I tried:
* installr -c -a "cmake zlib-dev" mgondan/rswipl
* installr -c -a "cmake zlib-dev" local::rswipl
* cd rswipl; installr -c -a "cmake zlib-dev" local::.
* cd rswipl; installr -c -a "cmake zlib-dev" url::file:///home/gondan/rswipl_9.3.3.2.tar.gz

with different error messages (the one from mgondan/rswipl suggesting that the "submodule" swipl-devel wasn't loaded, the others incomprehensible)

**Comment by bastistician** [comment]
I originally observed the installation failure on a native Alpine Linux server that installs thousands of R packages. The 'r-minimal' docker image can be useful when reporting such issues as it enables others to reproduce them on their own machine.

To access a local file from your host system from within a docker container, you can use a bind mount via the `-v` flag. For example, to mount your `~/Downloads` in your container at `/Downloads` and install a package tarball from there:
```sh
docker run -v ~/Downloads:/Downloads rhub/r-minimal  installr -c -a "cmake zlib-dev" /Downloads/rswipl_9.3.3.1.tar.gz
```

**Comment by mgondan** [comment]
Just to let you know that I can now reproduce the problem using the command you describe above. Unfortunately, I haven't yet found a fix. And if I install Alpine Linux on my computer (on Windows with WSL2), swi-prolog doesn't compile properly, so this may take a bit.

**Comment by mgondan** [comment]
The current git should now work on Alpine Linux, as well. I think it has to do with the limited support for "lazy loading of shared libraries" on musl.

**Comment by bastistician** [comment]
Great! I was really just about to reply: "Thanks for investigating! At least this is a known issue now. :) It can probably be put on hold until it affects more users (Alpine Linux is a minority OS)."
Will give it a try on my system.

**Comment by bastistician** [comment]
Unfortunately, I cannot confirm success. Now src compilation fails with
```
g++ -std=gnu++17 -I"/mnt/QA/R-86380/build/include" -DNDEBUG -Iswipl-devel/src -I../inst/swipl/lib/swipl/include -D_REENTRANT -D__SWI_PROLOG__ -D__SWI_EMBEDDED__ -I'/mnt/QA/R-86380/lib/Rcpp/include' -I/usr/local/include   -fvisibility=hidden -fpic  -O2 -mtune=native -Wno-ignored-attributes -Wno-deprecated-declarations -D__MUSL__   -c rswipl.cpp -o rswipl.o
rswipl.cpp:3:10: fatal error: SWI-cpp2.h: No such file or directory
    3 | #include <SWI-cpp2.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
using either of the two recent commits 130000a or dcee496.

**Comment by mgondan** [comment]
Just to make sure, since this doesn't work here either:

`docker run -v ~/Downloads:/Downloads rhub/r-minimal installr -c -a "cmake zlib-dev" mgondan/rswipl`

Instead, I need to clone rswipl, update the submodules recursively, then build, then use the mount point as you have shown to me above:

````
git clone https://github.com/mgondan/rswipl
cd rswipl
git submodule update --init --remote --recursive
cd ..
R CMD build rswipl
mkdir Downloads
mv rswipl_9.3.3.2.tar.gz Downloads
docker run -v ~/Downloads:/Downloads rhub/r-minimal  installr -c -a "cmake zlib-dev" /Downloads/rswipl_9.3.3.2.tar.gz
````

**Comment by bastistician** [comment]
Good catch! Missing submodules, indeed. Specifically, I had not used the `--recursive` and the `--remote` flags when updating the submodules. I have now simply used

    git clone --recurse-submodules --remote-submodules  https://github.com/mgondan/rswipl

With this (and using current 3c249a8) installation succeeds and tests pass! So I think this can be closed. :+1: 

( Testing that "check_installation works" shows "Warning: Found 21 issues.", but [that seems to be expected](https://github.com/mgondan/rswipl/blob/3c249a81e8681f18c0fb0d124ba2ca60d238b9aa/tests/testthat/test-rswipl.R#L220). )

**Comment by mgondan** [comment]
That's too many. Would you mind to send me those warnings (either here or via email)

**Comment by bastistician** [comment]
I was seeing 20 instances of
```
Warning: library(<libname>) ......................... NOT FOUND
```
but that is very similar to the test output from the latest check jobs run on GitHub, so I am not concerned. Compared to the [ubuntu run](https://github.com/mgondan/rswipl/actions/runs/8737615886/job/23974968470#step:6:246) with its 19 "NOT FOUND" warnings, I get an additional one for `library(yaml)`.

**Comment by mgondan** [comment]
You're right. These swipl packages have not been included in rswipl (they are excluded in .Rbuildignore).

Ok, case closed. Thank you for reporting.
